# Based off of https://github.com/lowlighter/metrics
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * 1"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GH_METRICS }}
          # Repository-specific GITHUB_TOKEN for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # Fancy isometric calendar
          filename: metrics.plugin.isocalendar.svg
          plugin_isocalendar: yes
          # Options
          user: zurdala
          template: classic
          base: header, activity, community, repositories, metadata
          config_animations: yes
          config_timezone: Europe/Berlin
          plugin_introduction: yes
          plugin_languages: yes
          plugin_languages_ignored: less, dockerfile, qmake, lex
          plugin_habits: yes
          plugin_habits_from: 250
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_lines: yes
          plugin_lines_delay: 30

